# Generated by Django 4.0.4 on 2022-08-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
